---
# tasks file for gcp_instance
- name: create a disk for a webserver instance 
  gcp_compute_disk:
      name: 'disk-instance-1'
      size_gb: 50

      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: disk1

- name: create a address
  gcp_compute_address:
      name: 'address-instance-1'
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: address1

- name: create a instance
  gcp_compute_instance:
      state: present
      name: web-app-1
      machine_type: n1-standard-1
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk1 }}"
      network_interfaces:
          - network: null # use default
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address1 }}"
                type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: instance1

- name: Wait for SSH to come up
  wait_for: host={{ address1.address }} port=22 delay=10 timeout=60

- name: Add host to groupname
  add_host: hostname={{ address1.address }} groupname=new_instances1




- name: create a disk for the second websever
  gcp_compute_disk:
      name: 'disk-instance-2'
      size_gb: 50
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: disk2

- name: create a address 2
  gcp_compute_address:
      name: 'address-instance-2'
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: address2

- name: create a instance 2
  gcp_compute_instance:
      state: present
      name: web-app-2
      machine_type: n1-standard-1
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk2 }}"
      network_interfaces:
          - network: null # use default
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address2 }}"
                type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: instance2

- name: Wait for SSH to come up
  wait_for: host={{ address2.address }} port=22 delay=10 timeout=60

- name: Add host to groupname
  add_host: hostname={{ address2.address }} groupname=new_instances2


- name: create a disk for the databse server
  gcp_compute_disk:
      name: 'disk-instance-3'
      size_gb: 50
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: disk3

- name: create a address 3
  gcp_compute_address:
      name: 'address-instance-3'
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: address3

- name: create a instance 3
  gcp_compute_instance:
      state: present
      name: db_server
      machine_type: n1-standard-1
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk3 }}"
      network_interfaces:
          - network: null # use default
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address3 }}"
                type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: instance3

- name: Wait for SSH to come up
  wait_for: host={{ address2.address }} port=22 delay=10 timeout=60

- name: Add host to groupname
  add_host: hostname={{ address3.address }} groupname=new_instances3
