---
# tasks file for wordpress
- name: Create a wordpress app
  community.aws.cloudformation_stack_set:
    name: WebApp1-WordPress
    description: Deploy a WordPress App
    state: present
    accounts: '{{ ACCOUNTS }}'
    template: /c/Users/teeja/Desktop/Projects/aws-arch/cloud_formation_template/webapp/staticwebapp.yaml
    regions:
    - us-east-1