---
# tasks file for vpc
- name: Create a stack of vpc
  community.aws.cloudformation_stack_set:
    name: WebApp1-VPC
    description: create vpc in aws account
    state: present
    accounts: '{{ ACCOUNTS }}'
    template: /c/Users/teeja/Desktop/Projects/aws-arch/cloud_formation_template/webapp/vpc-alb-app-db.yaml
    regions:
    - us-east-1

    